# S3 (MinIO) probe config
s3:
  defaultDuration: 2s
  clusters:
    - name: minio-test
      endpoint: http://127.0.0.1:9000
      region: us-east-1
      accessKey: minioadmin
      secretKey: minioadmin
      bucket: test-s3-bucket
      useSSL: false
      duration: 5s
      tasks:
        read: true
        write: true
      # The probe will use the object key "probe-test-file" for read/write

# Global default duration for all probes (Go duration string, e.g. 10s, 500ms)
defaultDuration: 10s

# Per-type default duration (overrides global default for that type)
redisDefaultDuration: 15s
redisClusterDefaultDuration: 20s
# mysqlDefaultDuration: 30s
# kafkaDefaultDuration: 25s

# Example for mysql (single node, read+write)
mysql:
  defaultDuration: 2s  # optional, overrides global and per-type for mysql
  clusters:
    - name: main-mysql
      user: testuser
      password: testpass
      database: testdb
      duration: 5s
      read_hosts:
        - 127.0.0.1:3306
      write_hosts:
        - 127.0.0.1:3306

# Example for redis (single node)
redis:
  defaultDuration: 5s  # optional, overrides global and per-type for redis
  clusters:
    - name: main-redis
      nodes:
        - 127.0.0.1:6379
      password: ""
      duration: 5s     # optional, overrides all above for this cluster
      tasks:
        read: true
        write: true

redisCluster:
  defaultDuration: 18s  # optional, overrides global and per-type for redisCluster
  clusters:
    - name: test-redis-cluster
      nodes:
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
      password: ""
      duration: 5s      # optional, overrides all above for this cluster
      tasks:
        read: true
        write: true