defaultDuration: 5s
# Example for HTTP probe
http:
  defaultDuration: 10s
  clusters:
    - name: example-test-2
      endpoint: https://httpbin.org/status/200
      method: GET
      body: ""
      headers:
        User-Agent: Prober
      proxyURL: "http://localhost:8888"
      unacceptableStatusCodes: [500, 502, 500]
      timeout: 2s
      duration: 10s
      skipTLSVerify: false
      region: "us-east-1"  # <-- Add your region here
# S3 (MinIO) probe config
s3:
  defaultDuration: 5s
  clusters:
    - name: minio
      endpoint: http://127.0.0.1:9000
      region: us-east-1
      accessKey: minioadmin
      secretKey: minioadmin
      bucket: test-s3-bucket
      useSSL: false
      duration: 10s
      timeout: 200ms
      tasks:
        read: true
        write: true
      # The probe will use the object key "probe-test-file" for read/write

# # Example for mysql (single node, read+write)
mysql:
  defaultDuration: 5s  # optional, overrides global and per-type for mysql
  clusters:
    - name: test
      user: testuser
      password: testpass
      database: testdb
      duration: 10s
      read_query: "SELECT 1"
      write_query: "SELECT 1"
      read_hosts:
        - 127.0.0.1:3306
      write_hosts:
        - 127.0.0.1:3306
      region: "us-east-1"  # <-- Add your region here
      tasks:
        read: true
        write: true


# # Example for redis (single node)
redis:
  defaultDuration: 5s  # optional, overrides global and per-type for redis
  clusters:
    - name: test
      nodes:
        - 127.0.0.1:6379
      password: ""
      duration: 10s     # optional, overrides all above for this cluster
      region: "us-east-1"  # <-- Add your region here
      tasks:
        read: true
        write: true

redisCluster:
  defaultDuration: 5s  # optional, overrides global and per-type for redisCluster
  clusters:
    - name: test
      nodes:
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
      password: ""
      duration: 10s      # optional, overrides all above for this cluster
      region: "us-east-1"  # <-- Add your region here
      tasks:
        read: true
        write: true

# TCP probe config
# Probes google.com:443 every 5 minutes

tcp:
  defaultDuration: 1m
  clusters:
    - name: local
      region: us-east-2
      addresses:
        - 127.0.0.1:6379
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
    - name: google
      addresses:
        - google.com:443
        - gmail.com:443
      duration: 1m
      timeout: 2s
      region: "us-east-1"  # <-- Add your region here
